import Link from 'next/link';
import Layout from '../components/Layout';
import Head from 'next/head';
import styles from '../styles/Home.module.css';

const Home = () => (
  <div className={styles.container}>
    <Head>
      <title>Create Next App</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>

    <main className={styles.main}>
      <h1 className={styles.title}>
        Mikkeller Running Club <span className={styles.highlight}>Helsinki</span>
      </h1>

      <div className={styles.description}>
        <p>Our religion is running, and our temple is where great beer is served.</p>
        <p>
          We welcome all. It doesn't matter if you do it to compete, to stay in shape or just to take your mind off the
          everyday. What matters is that you lace up — and have tons of fun.
        </p>
        <p>
          {' '}
          We don't discriminate against any gender, orientation, color or creed. Like beer, runners come in all sizes,
          shapes and forms. Thus we won't tolerate body shaming, racism or harassment of any kind. Ever. We are one
          tribe — runners and beer drinkers all.
        </p>
        <p>
          At this club... There's always a place at the table. There's always good stories. There's always a feeling of
          togetherness.
        </p>
        <p>
          Ours is a table with friendly faces, frequent toasts and camaraderie. In this club, nobody gets excluded, left
          behind or left by the wayside.
        </p>
        <p>
          We didn't choose running, running chose us. We didn't choose beer, beer chose us. We are family. We are MRC
          Helsinki
        </p>
      </div>
    </main>

    {/* <main className={styles.main}>
      <h1 className={styles.title}>
        Welcome to <a href="https://nextjs.org">Next.js!</a>
      </h1>

      <p className={styles.description}>
        Get started by editing <code className={styles.code}>pages/index.js</code>
      </p>
    </main> */}
  </div>
);

export default Home;
